[tool.ruff]
# Используем современный стандарт длины строки.
line-length = 88
# Оставляем остальные ваши настройки
respect-gitignore = false
show-fixes = true
src = ["backend/src"]
include = ["backend/**/*.py"]
extend-exclude = ["settings.py", "*/migrations/", "data/"]


[tool.ruff.lint]
# ВЫБИРАЕМ ОСНОВНОЙ НАБОР ПРАВИЛ:
# E - ошибки pycodestyle
# W - предупреждения pycodestyle
# F - ошибки Pyflakes (неиспользуемые переменные и импорты)
# I - сортировка импортов (isort)
# S - уязвимости безопасности (bandit)
# B - распространенные ошибки (flake8-bugbear)
select = ["E", "W", "F", "I", "S", "B"]

# ИГНОРИРУЕМ КОНКРЕТНЫЕ, НАЗОЙЛИВЫЕ ПРАВИЛА:
# Мы не включали "D" (докстринги) в select, поэтому большинство D-ошибок
# и так исчезнет. Но если какое-то правило из выбранных категорий
# (например, из "B") будет мешать, его можно добавить сюда.
# D100, D101, D102, D103, D104, D105, D106, D107 - самые частые ошибки докстрингов,
# если вы решите вернуть "D" в select, можете добавить их сюда в ignore.
ignore = [
  # "B008": Не требовать делать вызов функции зависимостью в FastAPI/Django.
  # "S101": Разрешить использование assert (полезно в тестах).
]

# Остальные ваши настройки можно оставить как есть, они хорошие
[tool.ruff.lint.isort]
relative-imports-order = "closest-to-furthest"
split-on-trailing-comma = false

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = true
