volumes:
  postgres_data:
  static:
  media:


services:
  db:
    container_name: db_PostgreSQL
    image: registry.hub.docker.com/library/postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"] 
      interval: 5s
      timeout: 5s 
      retries: 30 

  backend:
    container_name: backend_Django
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static:/django_static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy
    env_file: ../.env

  frontend:
    container_name: frontend_React
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file: ../.env
  
  gateway:
    container_name: proxy_Nginx
    build:
      context: ../.
      dockerfile: nginx/Dockerfile
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/media
    restart: always
    depends_on:
      - backend
      - frontend
